apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nasco-nodejs-template
  name: nasco-nodejs-template
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nasco-nodejs-template
  template:
    metadata:
      labels:
        app: nasco-nodejs-template
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/project-test1/nasco-nodejs-template
          imagePullPolicy: Always
          name: nasco-nodejs-template
          ports:
            - containerPort: 5000
              protocol: TCP
