apiVersion: v1
kind: Service
metadata:
  labels:
    app: nasco-nodejs-template
  name: nasco-nodejs-template
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: nasco-nodejs-template
