const PERSONA_TYPE_ID = {
  INDIVIDUAL: 1230,
  COMPANY: 1231,
};

const PERSONA_STATUS_CODE = {
  NEW: 'NW',
  DUPLICATE: 'DP',
  REVIEW: 'RW',
  VALID: 'VL',
};

const COUNTRIES_CODE = {
  LEBANON: 'LBN',
  USA: 'USA',
  UAE: 'ARE',
  CANADA: 'CAN',
};

const PROFILE_TYPE_CODE = {
  BROKER: 'BRK',
  INSURED: 'INS',
  INSURER: 'INSR',
  INSURER_REP: 'INSR-REP',
  SUB_BROKER: 'SUB-BRK',
};

const GENDER_CODE = {
  FEMALE: 'F',
  MALE: 'M',
};

const PERSONA_TYPE_CODE = {
  INDIVIDUAL: 'IND',
  COMPANY: 'COMP',
  GROUP: 'GP',
};

const COMPANIES_CODE = {
  BANKERS: 'BNK',
  AIAW: 'AIAW',
};

module.exports = {
  COMPANIES_CODE,
  COUNTRIES_CODE,
  GENDER_CODE,
  PERSONA_STATUS_CODE,
  PERSONA_TYPE_ID,
  PROFILE_TYPE_CODE,
  PERSONA_TYPE_CODE,
};
